x-proxyconf:
  url: http://localhost:8080/api-key-in-query
  security:
    auth:
      downstream:
        type: query
        name: my-api-key
        clients:
          testUser:
            # md5sum of supersecret
            - 9a618248b64db62d15b300a07b00580b

openapi: 3.0.3
info:
  title: API Key in Query Parameter
  summary: Downstream Authentication
  description: |
    Authentication using an API key query parameter can be easily configured using the [Authentication with Header or Query Parameter or Header](../config/DownstreamAuth.md/#header-or-query-parameter) configuration.
  version: 0.1.0
servers:
  - url: http://127.0.0.1:4040/echo
paths:
  /test:
    get:
      parameters:
        - name: my-api-key
          in: query
          schema:
            type: string
      responses:
        '200':
          description: "OK"
