x-proxyconf:
  cluster: {{envoy-cluster}}
  url: http://localhost:8080/basic-auth
  security:
    auth:
      downstream:
        type: basic
        clients:
          myUser:
            # echo -n "myuser:mysecret" | md5sum
            - 25be91d02dbbf17aff80e21323cd0dc5

openapi: 3.0.3
info:
  title: Basic Authentication
  summary: Downstream Authentication
  description: |
    Authentication using HTTP Basic Authentication can be easily configured using the [Basic Authentication](../config/DownstreamAuth.md/#basic-authentication) configuration.
  version: 0.1.0
servers:
  - url: https://127.0.0.1:{{api-port}}/api/echo
paths:
  /test:
    get:
      responses:
        '200':
          description: "OK"
