x-proxyconf:
  url: http://localhost:8080/disabled
  security:
    auth: 
      downstream: disabled

openapi: 3.0.3
info:
  title: Disabled
  summary: Downstream Authentication
  description: |
    Opting out of downstream authentication by setting the [Disabled Flag](../config/DownstreamAuth.md/#disabled).
  version: 0.1.0
servers:
  - url: http://127.0.0.1:4040/echo
paths:
  /test:
    get:
      responses:
        '200':
          description: "OK"
