x-proxyconf:
  cluster: {{envoy-cluster}}
  url: https://localhost:8443/downstream-tls
  listener:
    address: 127.0.0.1
    port: 8443
  security:
    auth:
      downstream: disabled

openapi: 3.0.3
info:
  title: Downstream TLS
  summary: Misc
  description: |
    Downstream TLS is implicitely configured by providing a `https` URL in the `x-proxyconf.url` configuration. The server certificate used for the listener is selected by matching the `x-proxyconf.url` hostname with the TLS Common Name (CN) or TLS Subject Alternative Names (SAN) found in the TLS certificates available in [PROXYCONF_SERVER_DOWNSTREAM_TLS_PATH](../config/environment.md/#proxyconf_server_downstream_tls_path).
  version: 0.1.0
servers:
  - url: https://127.0.0.1:{{api-port}}/api/echo
paths:
  /test:
    get:
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              example: '{"hello":"world"}'
              schema:
                type: object
    post:
      requestBody:
        required: true
        content:
          application/json: {}
      responses:
        '200':
          description: "OK"
          content:
            application/json: {}
          
          
