x-proxyconf:
  cluster: {{envoy-cluster}}
  url: http://localhost:8080/jwt
  security:
    auth:
      downstream:
        type: jwt
        provider-config:
          issuer: proxyconf
          audiences: 
            - {{envoy-cluster}}
          remote_jwks:
            http_uri:
              uri: http://127.0.0.1:{{api-port}}/api/jwks.json
              timeout: 1s
            cache_duration:
              seconds: 300
openapi: 3.0.3
info:
  title: JSON Web Tokens (JWT)
  summary: Downstream Authentication
  description: |
    Authentication using JWT can be easily configured using the [Authentication with JWT](../config/DownstreamAuth.md/#json-web-tokens-jwt) configuration.
  version: 0.1.0
servers:
  - url: http://127.0.0.1:{{api-port}}/api/echo
paths:
  /test:
    get:
      responses:
        '200':
          description: "OK"
