x-proxyconf:
  cluster: {{envoy-cluster}}
  url: https://localhost:44444/mtls
  listener:
    address: "127.0.0.1"
    port: 44444
  security:
    auth:
      downstream:
        type: mtls
        trusted-ca: test/support/certs/snakeoil-ca.crt
        clients:
          test_client:
            - demo-client

openapi: 3.0.3
info:
  title: Mutual TLS (mTLS)
  summary: Downstream Authentication
  description: |
    Authenticate using TLS client certificates (mTLS).
  version: 0.1.0
servers:
  - url: https://127.0.0.1:{{api-port}}/api/echo
paths:
  /test:
    get:
      responses:
        '200':
          description: "OK"
