x-proxyconf:
  cluster: {{envoy-cluster}}
  url: http://localhost:8080/routing-misc
  security:
    auth: 
      downstream: disabled

openapi: 3.0.3
info:
  title: ProxyConf Showcasing different Routing Scenrios
  version: 0.1.0
servers:
  - url: http://127.0.0.1:{{api-port}}/api/echo
paths:
  /test:
    get:
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              example: '{"hello":"world"}'
              schema:
                type: object
    post:
      requestBody:
        required: true
        content:
          application/json: {}
      responses:
        '200':
          description: "OK"
          content:
            application/json: {}
          
          
