name: CI
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  build:
    name: CI
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('**/flake.nix') }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ matrix.os }}-mix-${{ hashFiles('**/flake.nix') }}-
      - name: Run Processes
        run: |
          nix develop --impure --command -- devenv up &
      - name: Run CI
        run: |
          nix develop --impure --command -- run-ci commons
          nix develop --impure --command -- run-ci cli
          nix develop --impure --command -- run-ci control_plane
